// global using global::Microsoft.eShopOnContainers.Services.Ordering.Domain.Exceptions;
global using MediatR;
global using Schedule.Domain.Common;
// global using Microsoft.eShopOnContainers.Services.Ordering.Domain.AggregatesModel.BuyerAggregate;
// global using Microsoft.eShopOnContainers.Services.Ordering.Domain.AggregatesModel.OrderAggregate;
// global using Microsoft.eShopOnContainers.Services.Ordering.Domain.Events;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Threading;
global using System;